In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

In [178]:
# Importing the dataset
#dataset = pd.read_csv('full.csv', delimiter='|')
#X = dataset.iloc[:, :-1].values
#y = dataset.iloc[:, 3].values

def get_dataset(first_class = 'H', max_N=0):
    
    id = 0
    classes = {}
    X = []
    y = []
    
    with open('full.csv', 'r', encoding="utf8") as file:
        i_N = 0
        for line in file:
            if max_N == 0 or i_N < max_N:
                data = line.split('|')
                if len(data) == 7:
                    data_classes = data[1].split(',')
                    cl_set = set()
                    for cl in data_classes:
                        c = cl.upper()
                        c = c.replace(' ', '')
                        a = re.search(r'([A-H])([0-9]{2})([A-Z])', c, re.M|re.I)
                        try:
                            if a.group(1) == first_class:
                                cl_set.add(id)
                                if (a.group(1) + a.group(2) + a.group(3)) not in classes:
                                    classes[a.group(1) + a.group(2) + a.group(3)] = id
                                    id += 1 
                        except:
                            pass
                    if len(cl_set) > 0:
                        X.append([data[2], data[3]])
                        y.append(list(cl_set))
                        i_N += 1
    return [X, y, classes]

In [213]:
dataset = get_dataset(first_class = 'H') #, max_N = 1000)

In [214]:
X = dataset[0]
y = dataset[1]

from sklearn.preprocessing import MultiLabelBinarizer
y = MultiLabelBinarizer().fit_transform(y)

In [215]:
# Cleaning the texts
import re
import nltk
corpus_titulo = []
corpus_resumo = []
for i in range(len(X)):
    titulo = X[i][1].split()
    resumo = X[i][0].split()
    for j in range(len(titulo)):
        titulo[j] = re.sub('[^a-zA-Z]', '', titulo[j])
    for j in range(len(resumo)):
        resumo[j] = re.sub('[^a-zA-Z]', '', resumo[j])
    titulo = ' '.join(titulo)
    resumo = ' '.join(resumo)
    corpus_titulo.append(titulo)
    corpus_resumo.append(resumo)

In [216]:
corpus_resumo[0]

'Envoltorio para maquinas eletricas'

In [217]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = None, ngram_range=(1,1))
X_titulo = cv.fit_transform(corpus_titulo)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = None, ngram_range=(1,1))
X_resumo = cv.fit_transform(corpus_resumo)

In [218]:
# svd
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=50)
X_titulo = svd.fit_transform(X_titulo)

from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=50)
X_resumo = svd.fit_transform(X_resumo)

In [219]:
# concatena titulo e resumo
X = np.concatenate((X_titulo, X_resumo), axis=1)

In [220]:
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=None)

In [221]:
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = None)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [222]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [223]:
y_pred[3]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.])

In [224]:
for i in range(len(y_test[0])):
    print(confusion_matrix(y_test[:, i], y_pred[:, i]))

[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3613    0]
 [   1    0]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3609    0]
 [   2    3]]
[[3613    0]
 [   1    0]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3611    0]
 [   3    0]]
[[3612    0]
 [   2    0]]
[[3613    0]
 [   1    0]]
[[3613    0]
 [   1    0]]
[[3612    0]
 [   2    0]]
[[3611    0]
 [   3    0]]
[[3614]]
[[3614]]
[[3614]]
[[3614]]
[[3612    0]
 [   2    0]]
[[3606    0]
 [   8    0]]
[[3609    0]
 [   5    0]]
[[3613    0]
 [   1    0]]
[[3601    0]
 [  13    0]]
[[3610    0]
 [   4    0]]
[[3588    0]
 [  26    0]]
[[3597    0]
 [  17    0]]
[[3614]]
[[3613    1]
 [   0    0]]
[[3602    0]
 [  12    0]]
[[3596    0]
 [  18    0]]
[[3611    0]
 [   3    0]]
[[3606    0]
 [   8    0]]
[[3600    0]
 [  14    0]]
[[3613    0]
 [   1    0]]
[[3614]]
[[  81  968]
 [  30 2535]]
[[2865    9]
 [ 714   26]]
[[3573    0]
 [  41    0]]
[

In [225]:
acc = []
for i in range(len(y_test[0])):
    acc.append(accuracy_score(y_test[:, i], y_pred[:, i]))

print('Media: ', np.array(acc).mean())
acc

Media:  0.990358376429


[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.99972329828444939,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.99944659656889878,
 0.99972329828444939,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.99916989485334806,
 0.99944659656889878,
 0.99972329828444939,
 0.99972329828444939,
 0.99944659656889878,
 0.99916989485334806,
 1.0,
 1.0,
 1.0,
 1.0,
 0.99944659656889878,
 0.99778638627559491,
 0.99861649142224684,
 0.99972329828444939,
 0.99640287769784175,
 0.99889319313779745,
 0.9928057553956835,
 0.9952960708356392,
 1.0,
 0.99972329828444939,
 0.99667957941339236,
 0.99501936912008859,
 0.99916989485334806,
 0.99778638627559491,
 0.99612617598229114,
 0.99972329828444939,
 1.0,
 0.72385168788046483,
 0.79994465965688988,
 0.98865522966242392,
 0.96956281128943]

In [226]:
dataset[2]

{'H01B': 16,
 'H01C': 8,
 'H01F': 6,
 'H01G': 13,
 'H01H': 1,
 'H01J': 17,
 'H01K': 18,
 'H01L': 30,
 'H01M': 19,
 'H01P': 35,
 'H01Q': 29,
 'H01R': 2,
 'H01S': 7,
 'H01T': 20,
 'H02B': 11,
 'H02C': 51,
 'H02G': 4,
 'H02H': 25,
 'H02J': 22,
 'H02K': 0,
 'H02M': 21,
 'H02N': 10,
 'H02P': 26,
 'H02R': 48,
 'H02S': 56,
 'H02V': 46,
 'H03B': 49,
 'H03C': 36,
 'H03D': 32,
 'H03F': 42,
 'H03G': 43,
 'H03H': 40,
 'H03J': 33,
 'H03K': 39,
 'H03L': 37,
 'H03M': 38,
 'H04B': 23,
 'H04D': 45,
 'H04G': 52,
 'H04H': 41,
 'H04J': 24,
 'H04K': 34,
 'H04L': 31,
 'H04M': 12,
 'H04N': 5,
 'H04Q': 14,
 'H04R': 3,
 'H04S': 28,
 'H04W': 54,
 'H05B': 15,
 'H05C': 27,
 'H05F': 50,
 'H05G': 53,
 'H05H': 47,
 'H05K': 9,
 'H61C': 44,
 'H99Z': 55}